### ISSUE TITLE
Namespacing of Rake tasks not working as expected when calling from an app

### ISSUE THREAD

**Issue by anarchivist** [dpla-attic/marmottawrapper#14]
As suggested, I'm trying to work with the branch referenced in dpla/marmottawrapper#13 to test dpla/KriKri#3.  Our `README` suggests that the tasks should be namespaced as `app:marmotta:$TASK`, but I don't see them there. (They are being loaded appropriately by Krikiri when you're a local working copy of the engine's `RAILS_ROOT`, and there the tasks show up as `marmotta:$TASK`.

**Comment by no-reply** [comment]
> They are being loaded appropriately by Krikiri when you're a local working copy of the engine's RAILS_ROOT, and there the tasks show up as marmotta:$TASK.

This is what is intended by #3, to make it possible to start marmotta from the root dir of your krikri project. Once this is merged, I expect to push an update to krikri's readme that corrects the namespace.

With `engine_cart`, I don't expect to have any tasks in the `app:` namespace.  I'm uncertain whether we need the generated app to have marmotta tasks, given that the `ci` task will be run from krikri, and developers will be working from their own local projects.

**Comment by anarchivist** [comment]
OK, this is 100% clearer to me now. Sorry for my denseness! :blush:

**Comment by no-reply** [comment]
ah ha! glad it wasn't me being dense.  As I've thought about it, seems like we _do_ want krikri to pass these tasks up so heidrun, etc... have access to them. But that wasn't a goal of this PR.

**Comment by anarchivist** [comment]
Yep. In that case would it be better to declare `marmottawrapper` as a development dependency of `heidrun`, etc.?
