### ISSUE TITLE
(Vagrantized) Marmotta should be accessed via localhost after being started but before rake task ends

### ISSUE THREAD

**Issue by anarchivist** [dpla-attic/marmottawrapper#8]
The Rake tasks should access the repository from localhost before finishing.  Marmotta has a freakout about port numbers if you access it through the vagrant net interfaces first.

Might also be a good idea for this to setup a default admin password; see http://marmotta.apache.org/platform/security-module.html:

``` bash
curl -X POST -H "Content-Type: application/json" -d '["standard"]' http://<HOST>:<PORT>/marmotta/config/data/security.profile
```

raised by @no-reply in a commit comment on #7

**Comment by no-reply** [comment]
You need to have access from both the virtual machine and the host machine to allow setting permissions as well as browser access.  The solution is probably to pin the ports together and make them configurable.
